# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tiquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=127)),
                ('contenido', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('estado', models.CharField(choices=[('CR', 'Creado'), ('TR', 'En trámite'), ('FI', 'Finalizado'), ('?', 'Información no disponible')], default='?', max_length=2)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiquetsapp.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiquetsapp.Tiquet'),
        ),
    ]
