# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto_comentario',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiquetsapp.Categoria'),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='contenido',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creado'), ('TR', 'En trámite'), ('FI', 'Finalizado')], default='CR', max_length=2),
        ),
    ]
