# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiquet',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tiquet',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 4, 8, 16, 1, 998467, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquet',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 4, 8, 16, 5, 110180, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto_comentario',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiquetsapp.Categoria'),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='contenido',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creado'), ('TR', 'En trámite'), ('FI', 'Finalizado')], default='CR', max_length=2),
        ),
    ]
