# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0002_auto_20160303_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiquet',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tiquet',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 3, 22, 49, 0, 514759, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiquet',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 3, 22, 49, 17, 77708, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
