# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0002_auto_20160304_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiquet',
            old_name='modificado',
            new_name='last_update',
        ),
    ]
