# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0003_auto_20160304_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiquet',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tiquet',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
