# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiquetsapp', '0004_auto_20160304_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
    ]
